# 唯一的主面板：纯手动节点组
custom_proxy_group=📌 手动选择`select`.*

# 路由规则（全部指向“📌 手动选择”）
ruleset=DIRECT,https://raw.githubusercontent.com/PM100Fun/subconverter-mod/master/base/force-direct.list
ruleset=📌 手动选择,https://raw.githubusercontent.com/PM100Fun/subconverter-mod/master/base/force-proxy.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=📌 手动选择,[]MATCH