# 唯一的主面板：自动测速组（带 150ms 容差和极速测速链接）
custom_proxy_group=♻️ 自动测速`url-test`.*`http://1.1.1.1/generate_204`300,,150

# 路由规则（全部指向“♻️ 自动测速”）
ruleset=DIRECT,https://raw.githubusercontent.com/PM100Fun/subconverter-mod/master/base/force-direct.list
ruleset=♻️ 自动测速,https://raw.githubusercontent.com/PM100Fun/subconverter-mod/master/base/force-proxy.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=♻️ 自动测速,[]MATCH